--case_study_2
--Group By & Having Clause:

--How many employees who are working in different departments wise in the organization
SELECT DEPARTMENT_ID,COUNT(*) AS "NUMBER OF EMPLOYEE"
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID


--List out the department wise maximum salary, minimum salary, average salary of the employees
SELECT  DEPARTMENT_ID, MAX(SALARY) MAXUM_SALARY,MIN(SALARY) MINMUM_SALARY,AVG(SALARY) AVERAGE_SALARY
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID


--List out the job wise maximum salary, minimum salary, average salaries of the employees.
SELECT  JOB_ID,MAX(SALARY) MAXUM_SALARY, MIN(SALARY) MINMUM_SALARY,AVG(SALARY) AVERAGE_SALARY
FROM EMPLOYEE
GROUP BY JOB_ID

--List out the no.of employees joined in every month in ascending order.
SELECT DATENAME(MM,HIREDATE) MONTH,COUNT(*) NoOfEmployee
FROM EMPLOYEE
GROUP BY DATENAME(MM,HIREDATE)

--List out the no.of employees for each month and year, in the ascending order based on the year, month.
SELECT  DATEPART(YYYY,HIREDATE) YEAR,DATENAME(MM,HIREDATE) MONTH, COUNT(*) NoOfEmployee
FROM EMPLOYEE
GROUP BY DATEPART(YYYY,HIREDATE),DATENAME(MM,HIREDATE)    
             

--List out the department id having at least four employees.
SELECT DEPARTMENT_ID,COUNT(*) "NUMBER OF EMPLOYEES"
FROM EMPLOYEE
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>4

--How many employees in January month.

 SELECT DATENAME(MM,HIREDATE) MONTH,COUNT(*) "NUMBER OF EMPLOYEES"
FROM EMPLOYEE
WHERE DATENAME(MM,HIREDATE)='FEBRUARY'
GROUP BY DATENAME(MM,HIREDATE)

--How many employees who are joined in January or September month.

SELECT DATENAME(MM,HIREDATE) MONTH,COUNT(*) "NUMBER OF EMPLOYEES"
FROM EMPLOYEE
WHERE DATENAME(MM,HIREDATE)IN ('FEBRUARY','MARCH')
GROUP BY DATENAME(MM,HIREDATE)

--How many employees who are joined in 1985.
SELECT DATEPART(YY,HIREDATE) YEAR,COUNT(*) "NUMBER OF EMPLOYEES"
FROM EMPLOYEE
WHERE DATEPART(YY,HIREDATE)=1985
GROUP BY DATEPART(YY,HIREDATE)


--How many employees joined each month in 1985.
SELECT  DATEPART(YY,HIREDATE) YEAR, DATENAME(MM,HIREDATE) MONTH,COUNT(*) "NUMBER OF EMPLOYEES"
FROM EMPLOYEE
WHERE DATEPART(YY,HIREDATE)=1985
GROUP BY DATEPART(YY,HIREDATE),DATENAME(MM,HIREDATE)            

--How many employees who are joined in March 1985.

SELECT      DATEPART(YY,HIREDATE) YEAR, DATENAME(MM,HIREDATE) MONTH,COUNT(*) "NUMBER OF EMPLOYEES"
FROM  EMPLOYEE WHERE DATEPART(YY,HIREDATE)=1985  AND  DATENAME(MM,HIREDATE)='MARCH'
GROUP BY DATEPART(YY,HIREDATE),DATENAME(MM,HIREDATE)
            
--Which is the department id, having greater than or equal to 3 employees joined in April 1985.
 SELECT  DEPARTMENT_ID,COUNT(*) "NUMBER OF EMPLOYEES" FROM  EMPLOYEE
WHERE DATEPART(YY,HIREDATE)=1985 AND DATENAME(MM,HIREDATE)='APRIL'
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>=3            
