
--case_study_ 2 
-- joins 

-- 48.List our employees with their department names
SELECT EMPLOYEE_ID,LAST_NAME,SALARY,E.DEPARTMENT_ID,NAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID

--49.Display employees with their designations (jobs)
 SELECT EMPLOYEE_ID,LAST_NAME,SALARY,E.DEPARTMENT_ID,FUNCTIONALITY
FROM EMPLOYEE E
INNER JOIN JOB J
ON E.JOB_ID=J.JOB_ID

--50.Display the employees with their department name and regional groups.
SELECT EMPLOYEE_ID,LAST_NAME,SALARY,E.DEPARTMENT_ID,NAME,REGIONAL_GROUP
FROM EMPLOYEE E,DEPARTMENT D,LOCATION L
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
            AND
            D.LOCATION_ID=L.LOCATION_ID

--(OR)--

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,E.DEPARTMENT_ID,NAME,REGIONAL_GROUP
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
INNER JOIN LOCATION L ON D.LOCATION_ID=L.LOCATION_ID

--51.How many employees who are working in different departments and display with department name.
 SELECT NAME AS "DEPARTMENT NAME",COUNT(*) AS "NUMBER OF EMPLOYEES"
      FROM DEPARTMENT D
      INNER JOIN EMPLOYEE E
      ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
   GROUP BY NAME

--52.How many employees who are working in sales department.
 SELECT NAME,COUNT(*) AS "NUMBER OF EMPLOYEES"
      FROM DEPARTMENT D
      INNER JOIN EMPLOYEE E
      ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
      GROUP BY NAME
      HAVING NAME='SALES'

--53.Which is the department having greater than or equal to 5 employees and display the department names in ascending order.
      SELECT NAME AS "DEPARTMENT NAME",COUNT(*) AS "NUMBER OF EMPLOYEES"
      FROM DEPARTMENT D
      INNER JOIN EMPLOYEE E
      ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
      GROUP BY NAME
   HAVING COUNT(*)>=5

--54.How many jobs in the organization with designations.
      SELECT FUNCTIONALITY,COUNT(*) AS "NO OF JOBS"
      FROM JOB J
      INNER JOIN EMPLOYEE E
      ON E.JOB_ID=J.JOB_ID
   GROUP BY FUNCTIONALITY

--55.How many employees working in “New York”.
          SELECT REGIONAL_GROUP,COUNT(*) "NUMBER OF EMPLOYEES"
      FROM EMPLOYEE E
      INNER JOIN DEPARTMENT D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
      INNER JOIN LOCATION L ON D.LOCATION_ID=L.LOCATION_ID
      GROUP BY REGIONAL_GROUP
      HAVING REGIONAL_GROUP='DALLAS'
      --(OR)--
      SELECT REGIONAL_GROUP,COUNT(*) "NUMBER OF EMPLOYEES"
      FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
      WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
      AND D.LOCATION_ID=L.LOCATION_ID
      AND L.REGIONAL_GROUP='DALLAS'
      GROUP BY REGIONAL_GROUP

--56.Display employee details with salary grades.
           SELECT LAST_NAME,SALARY,GRADE
      FROM EMPLOYEE E,SALARY_GRADE S
   WHERE SALARY BETWEEN LOWER_BOUND AND UPPER_BOUND

--57.List out the no. of employees on grade wise.
          SELECT GRADE,COUNT(*)
      FROM SALARY_GRADE S,EMPLOYEE E
      WHERE SALARY BETWEEN LOWER_BOUND AND UPPER_BOUND
      GROUP BY GRADE
   ORDER BY GRADE DESC

--58.Display the employ salary grades and no. of employees between 2000 to 5000 range of salary.
             SELECT GRADE,COUNT(*)
      FROM SALARY_GRADE S,EMPLOYEE E
      WHERE SALARY BETWEEN LOWER_BOUND AND UPPER_BOUND
      AND
      LOWER_BOUND>=2000 AND UPPER_BOUND<=5000
      GROUP BY GRADE
   ORDER BY GRADE